import { CreateElement, getImages } from "./utils.js";

const images = getImages(
  require.context("./images", false, /\.(png|jpe?g|svg)$/)
);

const loadHome = () => {
  const content = document.querySelector("#content");
  content.innerHTML = "";

  const promo = CreateElement("h2", null, "playfair-display-headline", "Promo");
  content.appendChild(promo);

  const boxContent = [
    {
      asset: images["seasonal.png"],
      headline: "Saisonry",
      text: "Taste the season! Limited-time flavors, only while they last!",
    },
    {
      asset: images["social-media-promo.png"],
      headline: "Saturday Socials",
      text: "Snap. Tag. Dine. Share your meal & enjoy a special treat!",
    },
    {
      asset: images["happy-hour.png"],
      headline: "It's Wine'sday",
      text: "Midweek made better—discover perfect pairings made for you!",
    },
  ];

  boxContent.forEach(({ asset, headline, text }) => {
    const box = CreateElement("div", null, "box");
    content.appendChild(box);
    const image = CreateElement("img", null, "box-img");
    image.src = asset;
    image.loading = "lazy";
    box.appendChild(image);
    const boxText = CreateElement("div", null, "box-text");
    box.appendChild(boxText);
    const headlineText = CreateElement("h3", null, "playfair-display-headline", headline);
    boxText.appendChild(headlineText);
    const description = CreateElement("p", null, "plus-jakarta-sans", text);
    boxText.appendChild(description);
  });

  const testimony = CreateElement(
    "p", null,
    "plus-jakarta-sans-italic",
    "Absolutely obsessed! The vibe is effortlessly chic, and every dish is as stunning as it is delicious. The truffle mushroom risotto was pure perfection, and the desserts? Next level. A must-visit spot for foodies and Instagram lovers alike!"
  );
  const testimonyGiver = CreateElement("p", null, "plus-jakarta-sans-italic", "- Amanda");
  const box = CreateElement("div", null, "testimony-box");
  content.appendChild(box);
  box.appendChild(testimony);
  box.appendChild(testimonyGiver);
};

function initFooter() {
  const body = document.querySelector("body");
  const footer = CreateElement("div", null, "footer");
  body.appendChild(footer);

  const creditImg = CreateElement("p", null, "plus-jakarta-sans", "Images generated by DALL-E");
  footer.appendChild(creditImg);

  const jktFont = CreateElement("p");
  const jktLink = CreateElement("a", null, "plus-jakarta-sans", "Plus Jakarta Sans");
  jktLink.href = "https://fonts.google.com/specimen/Plus+Jakarta+Sans";
  jktFont.appendChild(jktLink);
  footer.appendChild(jktFont);

  const playfair = CreateElement("p");
  const playfairLink = CreateElement("a", null, "playfair-display-headline", "Playfair Display");
  playfairLink.href = "https://fonts.google.com/specimen/Playfair+Display";
  playfair.appendChild(playfairLink);
  footer.appendChild(playfair);

  const creditFont = CreateElement("p", null, "plus-jakarta-sans", "Logo font by ");
  const fontMaker = CreateElement("a", null, "plus-jakarta-sans", "Typeline Studio");
  fontMaker.href = "https://www.dafont.com/photograph-signature.font";
  creditFont.appendChild(fontMaker);
  footer.appendChild(creditFont);
}

function initHome() {
  const body = document.querySelector("body");
  const header = CreateElement("div", null, "header");

  body.appendChild(header);

  const nav = CreateElement("nav");
  header.appendChild(nav);

  const ul = CreateElement("ul");
  nav.appendChild(ul);

  const buttons = [
    { text: "Home", class: "home" },
    { text: "Menu", class: "menu" },
    { text: "About", class: "about" },
  ];

  buttons.forEach(({ text, class: className }) => {
    const li = CreateElement("li");
    const button = CreateElement("button", null, className, text);
    button.classList.add("playfair-display-headline")
    li.appendChild(button);
    ul.appendChild(li);
  });
  const content = CreateElement("div", "content", null);

  body.appendChild(content);

  const logo = CreateElement("img", null, "logo");
  logo.src = images["logo-odin-project-resto.svg"];
  body.appendChild(logo);
  loadHome();
  initFooter();
}

export { loadHome, initHome };
